/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    FormEditor: typeof import('./src/components/FormEditor.vue')['default']
    FormViewer: typeof import('./src/components/FormViewer.vue')['default']
  }
}
